// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/animals/animals.proto

package animals

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Animal represents an animal with properties
type Animal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Animal) Reset() {
	*x = Animal{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Animal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Animal) ProtoMessage() {}

func (x *Animal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Animal.ProtoReflect.Descriptor instead.
func (*Animal) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{0}
}

func (x *Animal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Animal) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Animal) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Request/Response messages
type GetAnimalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimalsRequest) Reset() {
	*x = GetAnimalsRequest{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalsRequest) ProtoMessage() {}

func (x *GetAnimalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalsRequest.ProtoReflect.Descriptor instead.
func (*GetAnimalsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{1}
}

type GetAnimalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animals       []*Animal              `protobuf:"bytes,1,rep,name=animals,proto3" json:"animals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimalsResponse) Reset() {
	*x = GetAnimalsResponse{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalsResponse) ProtoMessage() {}

func (x *GetAnimalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalsResponse.ProtoReflect.Descriptor instead.
func (*GetAnimalsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnimalsResponse) GetAnimals() []*Animal {
	if x != nil {
		return x.Animals
	}
	return nil
}

type DeleteAnimalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnimalsRequest) Reset() {
	*x = DeleteAnimalsRequest{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnimalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnimalsRequest) ProtoMessage() {}

func (x *DeleteAnimalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnimalsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnimalsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{3}
}

type DeleteAnimalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnimalsResponse) Reset() {
	*x = DeleteAnimalsResponse{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnimalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnimalsResponse) ProtoMessage() {}

func (x *DeleteAnimalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnimalsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAnimalsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{4}
}

type AddAnimalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animal        *Animal                `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAnimalRequest) Reset() {
	*x = AddAnimalRequest{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAnimalRequest) ProtoMessage() {}

func (x *AddAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAnimalRequest.ProtoReflect.Descriptor instead.
func (*AddAnimalRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{5}
}

func (x *AddAnimalRequest) GetAnimal() *Animal {
	if x != nil {
		return x.Animal
	}
	return nil
}

type AddAnimalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animal        *Animal                `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAnimalResponse) Reset() {
	*x = AddAnimalResponse{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAnimalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAnimalResponse) ProtoMessage() {}

func (x *AddAnimalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAnimalResponse.ProtoReflect.Descriptor instead.
func (*AddAnimalResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{6}
}

func (x *AddAnimalResponse) GetAnimal() *Animal {
	if x != nil {
		return x.Animal
	}
	return nil
}

type GetAnimalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimalRequest) Reset() {
	*x = GetAnimalRequest{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalRequest) ProtoMessage() {}

func (x *GetAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalRequest.ProtoReflect.Descriptor instead.
func (*GetAnimalRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnimalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAnimalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animal        *Animal                `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimalResponse) Reset() {
	*x = GetAnimalResponse{}
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalResponse) ProtoMessage() {}

func (x *GetAnimalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_animals_animals_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalResponse.ProtoReflect.Descriptor instead.
func (*GetAnimalResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_animals_animals_proto_rawDescGZIP(), []int{8}
}

func (x *GetAnimalResponse) GetAnimal() *Animal {
	if x != nil {
		return x.Animal
	}
	return nil
}

var File_pkg_proto_animals_animals_proto protoreflect.FileDescriptor

const file_pkg_proto_animals_animals_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/animals/animals.proto\x12\aanimals\"J\n" +
	"\x06Animal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"\x13\n" +
	"\x11GetAnimalsRequest\"?\n" +
	"\x12GetAnimalsResponse\x12)\n" +
	"\aanimals\x18\x01 \x03(\v2\x0f.animals.AnimalR\aanimals\"\x16\n" +
	"\x14DeleteAnimalsRequest\"\x17\n" +
	"\x15DeleteAnimalsResponse\";\n" +
	"\x10AddAnimalRequest\x12'\n" +
	"\x06animal\x18\x01 \x01(\v2\x0f.animals.AnimalR\x06animal\"<\n" +
	"\x11AddAnimalResponse\x12'\n" +
	"\x06animal\x18\x01 \x01(\v2\x0f.animals.AnimalR\x06animal\"&\n" +
	"\x10GetAnimalRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x11GetAnimalResponse\x12'\n" +
	"\x06animal\x18\x01 \x01(\v2\x0f.animals.AnimalR\x06animal2\xa8\x02\n" +
	"\aAnimals\x12E\n" +
	"\n" +
	"GetAnimals\x12\x1a.animals.GetAnimalsRequest\x1a\x1b.animals.GetAnimalsResponse\x12N\n" +
	"\rDeleteAnimals\x12\x1d.animals.DeleteAnimalsRequest\x1a\x1e.animals.DeleteAnimalsResponse\x12B\n" +
	"\tAddAnimal\x12\x19.animals.AddAnimalRequest\x1a\x1a.animals.AddAnimalResponse\x12B\n" +
	"\tGetAnimal\x12\x19.animals.GetAnimalRequest\x1a\x1a.animals.GetAnimalResponseB+Z)github.com/craftizmv/DS/pkg/proto/animalsb\x06proto3"

var (
	file_pkg_proto_animals_animals_proto_rawDescOnce sync.Once
	file_pkg_proto_animals_animals_proto_rawDescData []byte
)

func file_pkg_proto_animals_animals_proto_rawDescGZIP() []byte {
	file_pkg_proto_animals_animals_proto_rawDescOnce.Do(func() {
		file_pkg_proto_animals_animals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_animals_animals_proto_rawDesc), len(file_pkg_proto_animals_animals_proto_rawDesc)))
	})
	return file_pkg_proto_animals_animals_proto_rawDescData
}

var file_pkg_proto_animals_animals_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_animals_animals_proto_goTypes = []any{
	(*Animal)(nil),                // 0: animals.Animal
	(*GetAnimalsRequest)(nil),     // 1: animals.GetAnimalsRequest
	(*GetAnimalsResponse)(nil),    // 2: animals.GetAnimalsResponse
	(*DeleteAnimalsRequest)(nil),  // 3: animals.DeleteAnimalsRequest
	(*DeleteAnimalsResponse)(nil), // 4: animals.DeleteAnimalsResponse
	(*AddAnimalRequest)(nil),      // 5: animals.AddAnimalRequest
	(*AddAnimalResponse)(nil),     // 6: animals.AddAnimalResponse
	(*GetAnimalRequest)(nil),      // 7: animals.GetAnimalRequest
	(*GetAnimalResponse)(nil),     // 8: animals.GetAnimalResponse
}
var file_pkg_proto_animals_animals_proto_depIdxs = []int32{
	0, // 0: animals.GetAnimalsResponse.animals:type_name -> animals.Animal
	0, // 1: animals.AddAnimalRequest.animal:type_name -> animals.Animal
	0, // 2: animals.AddAnimalResponse.animal:type_name -> animals.Animal
	0, // 3: animals.GetAnimalResponse.animal:type_name -> animals.Animal
	1, // 4: animals.Animals.GetAnimals:input_type -> animals.GetAnimalsRequest
	3, // 5: animals.Animals.DeleteAnimals:input_type -> animals.DeleteAnimalsRequest
	5, // 6: animals.Animals.AddAnimal:input_type -> animals.AddAnimalRequest
	7, // 7: animals.Animals.GetAnimal:input_type -> animals.GetAnimalRequest
	2, // 8: animals.Animals.GetAnimals:output_type -> animals.GetAnimalsResponse
	4, // 9: animals.Animals.DeleteAnimals:output_type -> animals.DeleteAnimalsResponse
	6, // 10: animals.Animals.AddAnimal:output_type -> animals.AddAnimalResponse
	8, // 11: animals.Animals.GetAnimal:output_type -> animals.GetAnimalResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_animals_animals_proto_init() }
func file_pkg_proto_animals_animals_proto_init() {
	if File_pkg_proto_animals_animals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_animals_animals_proto_rawDesc), len(file_pkg_proto_animals_animals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_animals_animals_proto_goTypes,
		DependencyIndexes: file_pkg_proto_animals_animals_proto_depIdxs,
		MessageInfos:      file_pkg_proto_animals_animals_proto_msgTypes,
	}.Build()
	File_pkg_proto_animals_animals_proto = out.File
	file_pkg_proto_animals_animals_proto_goTypes = nil
	file_pkg_proto_animals_animals_proto_depIdxs = nil
}
